# Python Class 10 — 100 NumPy Practice Exercises

## About this class

This class is different from Classes 1–9: instead of teaching new material, it is a **big bank of practice problems** to sharpen the NumPy skills from Class 9.

### Where these exercises come from

These 100 exercises are based on the well-known **"100 NumPy Exercises"** collection, originally created by **Nicolas P. Rougier** and maintained with contributions from the NumPy community (open-source, available at [github.com/rougier/numpy-100](https://github.com/rougier/numpy-100)). They are a widely used practice set across the data-science and Python community.

For this course, every exercise has been:
- **checked and re-run** on a current NumPy version to make sure it still works correctly (a few used older syntax that NumPy has since deprecated — those have been updated),
- **organized into three difficulty tiers** (matching the original ★☆☆ / ★★☆ / ★★★ ratings) so you can work through them in a sensible order,
- given a **short explanation** identifying the key idea or function used in the solution.

### How to use this notebook

1. Read the question.
2. **Try to solve it yourself first**, in a scratch cell — don't peek at the solution immediately.
3. Compare your attempt with the solution cell below the question.
4. Read the short explanation to understand *why* the solution works.

### Scope note

Some of the **Advanced (★★★)** exercises use NumPy features that go beyond what Class 9 covers (for example `np.einsum`, `stride_tricks`, structured/record arrays, and a bit of `scipy`/`pandas`). That is intentional — they are stretch goals. If a solution uses something unfamiliar, that is a good opportunity to look up the function's documentation yourself, which is itself an important real-world skill.

### Structure

- **Part 1 — Beginner (★☆☆):** direct practice of everything taught in Class 9.
- **Part 2 — Intermediate (★★☆):** combines multiple Class 9 ideas, and introduces a few closely related new functions.
- **Part 3 — Advanced (★★★):** challenging, real-world-style problems — great practice for technical interviews or research code.

# Part 1 — Beginner (★☆☆)

33 exercises in this part.

### Exercise 1 — Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

**💡 Key idea:** `import numpy as np` is the universal convention used throughout this course (see Class 9).

### Exercise 2 — Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

2.5.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hg727bee/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hg727bee/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.34.106.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.34.106.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hg727bee/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hg727bee/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas 

**💡 Key idea:** `np.__version__` shows the installed version; `np.show_config()` prints which low-level math libraries (like BLAS/LAPACK) NumPy is built against.

### Exercise 3 — Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**💡 Key idea:** `np.zeros(10)` creates a 1D array of 10 float zeros — the NumPy equivalent of an empty placeholder list.

### Exercise 4 — How to find the memory size of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


**💡 Key idea:** Every NumPy array reports `.size` (number of elements) and `.itemsize` (bytes per element); multiplying them gives total memory usage.

### Exercise 5 — How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
import numpy
help(numpy.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

**💡 Key idea:** Python's built-in `help()` function works on any NumPy function and prints its docstring directly in the terminal or notebook.

### Exercise 6 — Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**💡 Key idea:** Indexing works exactly like Class 4's lists: `Z[4]` is the 5th element (index starts at 0).

### Exercise 7 — Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**💡 Key idea:** `np.arange(10, 50)` is NumPy's version of Python's `range()` from Class 6, but it returns an array instead of a range object.

### Exercise 8 — Reverse a vector (first element becomes last) (★☆☆)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**💡 Key idea:** Slicing with a step of `-1` (`Z[::-1]`) reverses an array — the same slicing trick used on lists in Class 4.

### Exercise 9 — Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**💡 Key idea:** `.reshape(3, 3)` reorganizes a flat 1D array of 9 numbers into a 3×3 matrix, without changing the underlying data (see Class 9, Section 21).

### Exercise 10 — Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


**💡 Key idea:** `np.nonzero()` returns the indices of every element that is not zero.

### Exercise 11 — Create a 3x3 identity matrix (★☆☆)

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**💡 Key idea:** `np.eye(3)` builds a 3×3 identity matrix — 1s on the diagonal, 0s everywhere else (see Class 9, Section 35).

### Exercise 12 — Create a 3x3x3 array with random values (★☆☆)

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.18453102 0.51140343 0.67868935]
  [0.17354494 0.91230244 0.03924743]
  [0.8054793  0.67801475 0.23237669]]

 [[0.9971032  0.69689946 0.00508289]
  [0.73089426 0.58477124 0.04739039]
  [0.6378298  0.16142095 0.81149202]]

 [[0.92936996 0.66680228 0.39771926]
  [0.73298091 0.20151149 0.61222022]
  [0.1426881  0.61485846 0.96707288]]]


**💡 Key idea:** `np.random.random((3,3,3))` builds a 3D array (like Class 9, Section 13) filled with random decimals between 0 and 1.

### Exercise 13 — Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00672086982216602 0.9934024933850212


**💡 Key idea:** `.min()` and `.max()` scan the whole array and return its smallest and largest values.

### Exercise 14 — Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4651013337794975


**💡 Key idea:** `.mean()` adds up every element and divides by how many there are — the array's average.

### Exercise 15 — Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**💡 Key idea:** Slicing `Z[1:-1, 1:-1]` selects everything *except* the outer border, then setting it to `0` leaves only the border as `1`.

### Exercise 16 — How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**💡 Key idea:** `np.pad()` wraps an array in extra rows/columns filled with a chosen value — here, a border of zeros.

### Exercise 17 — What is the result of the following expression? (★☆☆)

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**💡 Key idea:** This is a classic 'gotcha' exercise: it shows that `np.nan` never equals anything (even itself!) and that floating-point arithmetic (`0.3 == 3*0.1`) can be surprisingly inexact.

### Exercise 18 — Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**💡 Key idea:** `np.diag(values, k=-1)` places `values` on a diagonal shifted `k` steps below the main diagonal.

### Exercise 19 — Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**💡 Key idea:** Slicing with a step of `2`, starting at different offsets for rows and columns, paints an alternating checkerboard pattern.

### Exercise 20 — Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


**💡 Key idea:** `np.unravel_index(99, (6,7,8))` converts a flat position (99) into its full (x, y, z) coordinates inside a 3D array of that shape.

### Exercise 21 — Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**💡 Key idea:** `np.tile()` repeats a small pattern (here, a 2×2 block) across a grid to build a larger checkerboard.

### Exercise 22 — Normalize a 5x5 random matrix (★☆☆)

In [22]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.32261014  0.39520752  1.55253365 -0.30015309  0.98317445]
 [ 0.48647258 -1.10363523 -1.66261921  0.84428527  0.29819486]
 [-1.16723598  1.26673113  1.03023167 -0.2784125   0.15524974]
 [-0.27569997 -1.4879236   1.1984495  -0.52999474  1.28252145]
 [-2.09124345  0.23374767 -1.39557504  0.30157761 -0.05849443]]


**💡 Key idea:** Subtracting the mean and dividing by the standard deviation rescales data so it is centered at 0 — a common preprocessing step in data science.

### Exercise 23 — Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

**💡 Key idea:** `np.dtype([...])` defines a **custom structured type** made of several named fields — here, four single-byte fields (r, g, b, a) that together describe one color.

### Exercise 24 — Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


**💡 Key idea:** `np.dot()` (or the `@` operator) performs real matrix multiplication, exactly like Class 9, Section 15 — not element-wise multiplication.

### Exercise 25 — Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


**💡 Key idea:** Boolean masking with `&` (from Class 9's comparison operators) selects every element in a range, and `*= -1` negates just those in place.

### Exercise 26 — What is the output of the following script? (★☆☆)

In [26]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


**💡 Key idea:** This shows that Python's built-in `sum()` and NumPy's `sum` (imported via `from numpy import *`) behave differently once NumPy overrides the name — a caution against `import *`.

### Exercise 28 — What are the result of the following expressions? (★☆☆)

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\SAAD\AppData\Local\Temp\ipykernel_21836\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\SAAD\AppData\Local\Temp\ipykernel_21836\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\SAAD\AppData\Local\Temp\ipykernel_21836\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


**💡 Key idea:** This exercise (also seen in Class 9, Part D) shows what NumPy does with undefined math: `0/0` and `0//0` produce warnings and special `nan`/`0` results instead of crashing.

### Exercise 29 — How to round away from zero a float array ? (★☆☆)

In [28]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 9. 10. -4.  4. -1.  7. -1.  3. -5.  4.]
[ 9. 10. -4.  4. -1.  7. -1.  3. -5.  4.]


**💡 Key idea:** `np.copysign(np.ceil(np.abs(Z)), Z)` rounds the *size* of each number up, then reattaches its original positive/negative sign — 'rounding away from zero'.

### Exercise 30 — How to find common values between two arrays? (★☆☆)

In [29]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 5 8 9]


**💡 Key idea:** `np.intersect1d()` returns the values that appear in both arrays — the array equivalent of Class 6's set intersection (`&`).

### Exercise 31 — How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

**💡 Key idea:** `np.seterr()` (or the `with np.errstate():` context manager) temporarily changes how NumPy reacts to warnings like division by zero.

### Exercise 32 — Is the following expressions true? (★☆☆)

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\SAAD\AppData\Local\Temp\ipykernel_21836\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

**💡 Key idea:** The square root of a negative real number is undefined and gives `nan`; `np.emath.sqrt()` instead switches to complex numbers, so the two are not equal.

### Exercise 33 — How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

C:\Users\SAAD\AppData\Local\Temp\ipykernel_21836\2994426679.py:1: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  yesterday = np.datetime64('today') - np.timedelta64(1)
C:\Users\SAAD\AppData\Local\Temp\ipykernel_21836\2994426679.py:3: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  tomorrow  = np.datetime64('today') + np.timedelta64(1)


**💡 Key idea:** `np.datetime64` and `np.timedelta64` let you do date arithmetic directly, similar in spirit to Python's own date objects.

### Exercise 38 — Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [33]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**💡 Key idea:** `np.fromiter()` builds an array directly from any Python generator or iterator, without first collecting the values into a list.

# Part 2 — Intermediate (★★☆)

32 exercises in this part.

### Exercise 27 — Consider an integer vector Z, which of these expressions are legal? (★★☆)

In [34]:
Z = np.arange(10)

# We try each expression in its own try/except (Class 8 style) so one
# illegal expression doesn't stop us from seeing the others.
expressions = {
    "Z**Z": lambda: Z**Z,
    "2 << Z >> 2": lambda: 2 << Z >> 2,
    "Z <- Z": lambda: Z <- Z,   # parsed as Z < (-Z)
    "1j*Z": lambda: 1j*Z,
    "Z/1/1": lambda: Z/1/1,
    "Z<Z>Z": lambda: Z<Z>Z,
}

for label, expr in expressions.items():
    try:
        expr()
        print(f"{label:12s} -> legal")
    except Exception as e:
        print(f"{label:12s} -> ILLEGAL ({type(e).__name__}: {e})")

Z**Z         -> legal
2 << Z >> 2  -> legal
Z <- Z       -> legal
1j*Z         -> legal
Z/1/1        -> legal
Z<Z>Z        -> ILLEGAL (ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all())


**💡 Key idea:** Surprisingly, only the last expression is illegal: chained comparisons like `Z<Z>Z` try to convert a whole array's comparison into a single `True`/`False`, which NumPy refuses to guess (the same ambiguity error you'd get writing `if some_array:`).

### Exercise 34 — How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**💡 Key idea:** `np.arange('2016-07', '2016-08', dtype='datetime64[D]')` generates every calendar day in a date range, one day at a time.

### Exercise 35 — How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

**💡 Key idea:** Passing `out=` to functions like `np.add()` writes the result directly into an existing array instead of creating a new one — saving memory on large arrays.

### Exercise 36 — Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[3. 5. 5. 2. 6. 9. 7. 4. 7. 0.]
[3. 5. 5. 2. 6. 9. 7. 4. 7. 0.]
[3. 5. 5. 2. 6. 9. 7. 4. 7. 0.]
[3 5 5 2 6 9 7 4 7 0]
[3. 5. 5. 2. 6. 9. 7. 4. 7. 0.]


**💡 Key idea:** Four different ways to drop the decimal part of a positive number: subtracting the remainder, floor division, `np.floor()`, and converting the dtype to `int`.

### Exercise 37 — Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**💡 Key idea:** Adding a 1D array of shape `(5,)` to a 2D array of shape `(5,5)` uses **broadcasting** (Class 9, Section 26) to add the same row pattern to every row.

### Exercise 39 — Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**💡 Key idea:** `np.linspace(0, 1, 11, endpoint=False)` creates 11 evenly-spaced points excluding 1, and slicing off the first `[1:]` also excludes 0.

### Exercise 40 — Create a random vector of size 10 and sort it (★★☆)

In [40]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.05851002 0.10163334 0.14674737 0.31256575 0.40175687 0.50686678
 0.68658766 0.87888915 0.90649528 0.92539832]


**💡 Key idea:** `.sort()` rearranges an array's own elements into ascending order, in place.

### Exercise 41 — How to sum a small array faster than np.sum? (★★☆)

In [41]:
# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

**💡 Key idea:** `np.add.reduce()` is the lower-level operation that `np.sum()` is built on top of; for very small arrays it can have less overhead.

### Exercise 42 — Consider two random array A and B, check if they are equal (★★☆)

In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


**💡 Key idea:** `np.allclose()` checks numeric closeness within a small tolerance (safer for floats), while `np.array_equal()` demands an exact match.

### Exercise 43 — Make an array immutable (read-only) (★★☆)

In [43]:
Z = np.zeros(10)
Z.flags.writeable = False

**💡 Key idea:** Setting `.flags.writeable = False` turns an array **read-only** — any attempt to change it afterward raises an error.

### Exercise 44 — Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.03491992 0.11651714 0.9313158  1.30115187 0.80928731 0.26834689
 0.33190601 0.23046412 0.60614071 0.27115954]
[0.44824341 0.83475238 0.36774976 0.81700586 0.55125083 1.40407358
 0.80358701 0.69709498 0.08426469 0.81391997]


**💡 Key idea:** Converting `(x, y)` cartesian coordinates to `(r, θ)` polar coordinates uses the Pythagorean theorem (`np.sqrt`) and `np.arctan2` for the angle.

### Exercise 45 — Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.63029167 0.         0.46900717 0.34917305 0.70503588 0.56195361
 0.08000157 0.53081353 0.31563982 0.53836008]


**💡 Key idea:** `.argmax()` finds the *index* of the largest value (not the value itself), which can then be used to overwrite it.

### Exercise 46 — Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


**💡 Key idea:** A **structured array** can store named sub-fields (here `x` and `y`) inside every element, and `np.meshgrid()` fills them with a coordinate grid.

### Exercise 47 — Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [47]:
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


**💡 Key idea:** A Cauchy matrix's `(i,j)` entry is `1/(x_i - y_j)`; `np.subtract.outer()` computes every possible pairwise difference at once.

### Exercise 48 — Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


**💡 Key idea:** `np.iinfo()` and `np.finfo()` report the smallest and largest values (and precision) representable by each integer/float type.

### Exercise 49 — How to print all the values of an array? (★★☆)

In [49]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**💡 Key idea:** `np.set_printoptions(threshold=...)` overrides NumPy's default habit of abbreviating very large arrays with `...` when printing.

### Exercise 50 — How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

73


**💡 Key idea:** Subtracting the target value from every element, taking the absolute value, and calling `.argmin()` finds the closest match in the array.

### Exercise 51 — Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


**💡 Key idea:** This structured array nests fields inside fields: a `position` field containing `(x,y)`, and a `color` field containing `(r,g,b)` — like a mini dictionary schema for every element.

### Exercise 52 — Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.27110318 0.57141169 0.73703152 0.72107347 0.27425155
  0.27972191 0.88019902 0.45448972 0.29310319]
 [0.27110318 0.         0.80483131 0.9446881  0.58326671 0.54533176
  0.35429055 0.82015903 0.21803324 0.56248523]
 [0.57141169 0.80483131 0.         0.1972436  0.94671919 0.39319281
  0.50978145 0.91407161 0.90645738 0.42327972]
 [0.73703152 0.9446881  0.1972436  0.         0.97571146 0.58730207
  0.61373568 0.8797856  1.01257756 0.6191697 ]
 [0.72107347 0.58326671 0.94671919 0.97571146 0.         0.9256537
  0.50030909 0.30483981 0.40066566 0.96253064]
 [0.27425155 0.54533176 0.39319281 0.58730207 0.9256537  0.
  0.42749534 1.01774361 0.72004906 0.04340712]
 [0.27972191 0.35429055 0.50978145 0.61373568 0.50030909 0.42749534
  0.         0.60883957 0.40048466 0.46616344]
 [0.88019902 0.82015903 0.91407161 0.8797856  0.30483981 1.01774361
  0.60883957 0.         0.67613977 1.05967053]
 [0.45448972 0.21803324 0.90645738 1.01257756 0.40066566 0.72004906
  0.40048466 0.676139

**💡 Key idea:** Computing every pairwise distance between 2D points by hand uses broadcasting twice; `scipy.spatial.distance.cdist()` does the same thing as one optimized library call.

### Exercise 53 — How to convert a float (32 bits) array into an integer (32 bits) in place? (★★☆)

In [53]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[35 77 53 52 94 15 34 78 73 80]


**💡 Key idea:** `.view(np.int32)` reinterprets the *same bytes* as a different type without copying data — a fast, low-level in-place conversion trick.

### Exercise 54 — How to read the following file? (★★☆)

In [54]:
import numpy as np
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
""")

Z = np.genfromtxt(
    s,
    delimiter=",",
    dtype=float,
    filling_values=np.nan
)

print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


**💡 Key idea:** `np.genfromtxt()` reads CSV-like text (Class 9, Section 19) and can automatically fill missing/blank values with `np.nan`.

### Exercise 55 — What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


**💡 Key idea:** `np.ndenumerate()` is the array version of Python's built-in `enumerate()` (Class 6) — it yields each element's full coordinate *and* its value.

### Exercise 56 — Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

**💡 Key idea:** Combining a distance grid (`np.sqrt(X*X+Y*Y)`) with `np.exp()` produces the classic bell-curve shape of a 2D Gaussian.

### Exercise 57 — How to randomly place p elements in a 2D array? (★★☆)

In [57]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**💡 Key idea:** `np.random.choice()` picks random unique positions, and `np.put()` writes a value into an array at those flat positions.

### Exercise 58 — Subtract the mean of each row of a matrix (★★☆)

In [58]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.41067234  0.23414843 -0.37445845 -0.16809176 -0.04814356  0.12899978
  -0.3856398   0.31507771 -0.10096502 -0.01159968]
 [-0.37496655  0.1351141   0.30457473  0.15100973 -0.17124354 -0.19432838
  -0.25565553  0.04209568  0.13876174  0.22463802]
 [-0.04448195 -0.28138136  0.00626183  0.08569173 -0.32686408  0.42273282
   0.06989989  0.13013149 -0.12958526  0.06759487]
 [ 0.12444406 -0.66328807  0.22991505  0.06775198  0.08011443  0.00551798
  -0.37165511 -0.06211324  0.29054321  0.2987697 ]
 [ 0.08190783  0.19983416 -0.1372371   0.01434041 -0.42092154  0.13937361
   0.10952698 -0.01007189 -0.39074228  0.41398981]]


**💡 Key idea:** `X.mean(axis=1, keepdims=True)` computes each row's average while keeping the array 2D, so it can be subtracted from `X` using broadcasting.

### Exercise 59 — How to sort an array by the nth column? (★★☆)

In [59]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 1 5]
 [1 1 1]
 [3 7 3]]
[[9 1 5]
 [1 1 1]
 [3 7 3]]


**💡 Key idea:** `Z[:, 1].argsort()` finds the row order that would sort column 1, and using that order to index `Z` reorders every row to match.

### Exercise 60 — How to tell if a given 2D array has null columns? (★★☆)

In [60]:
# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


**💡 Key idea:** `.any(axis=0)` / `.all(axis=0)` scan down each column to check whether every value (or any value) meets a condition — useful for spotting all-zero or all-NaN columns.

### Exercise 61 — Find the nearest value from a given value in an array (★★☆)

In [61]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5039727742573488


**💡 Key idea:** The same 'subtract, abs, argmin' pattern from exercise 50 also works for finding the closest value to any target.

### Exercise 62 — Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [62]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


**💡 Key idea:** `np.nditer()` is a low-level iterator that can walk over several arrays of different (but broadcastable) shapes at the same time.

### Exercise 63 — Create an array class that has a name attribute (★★☆)

In [63]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


**💡 Key idea:** Subclassing `np.ndarray` lets you attach your own extra attributes (like `.name`) to an array while keeping all of NumPy's normal behavior.

### Exercise 66 — Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [64]:
# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


**💡 Key idea:** `np.unique(..., axis=0)` finds distinct rows (here, distinct RGB colors) instead of distinct single values.

### Exercise 83 — How to find the most frequent value in an array? (★★☆)

In [65]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


**💡 Key idea:** `np.bincount(Z).argmax()` counts how often each value occurs, then finds which value has the highest count — the array's 'mode'.

# Part 3 — Advanced (★★★)

35 exercises in this part.

### Exercise 64 — Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [66]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 4. 2. 5. 3. 2. 3. 1. 5. 3.]
[3. 7. 3. 9. 5. 3. 5. 1. 9. 5.]


**💡 Key idea:** `np.bincount()` (or `np.add.at()`) correctly adds 1 for *every* occurrence of a repeated index — a plain loop would silently overwrite repeated updates.

### Exercise 65 — How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


**💡 Key idea:** `np.bincount(I, weights=X)` sums up values from `X` into 'buckets' named by the indices in `I` — a fast way to group-and-sum without a real loop.

### Exercise 67 — Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [68]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 55 48 40]
 [48 57 47 33]
 [54 48 63 61]]
[[57 55 48 40]
 [48 57 47 33]
 [54 48 63 61]]


**💡 Key idea:** `.sum(axis=(-2,-1))` sums over the last two axes at once by passing a tuple, avoiding two separate `.sum()` calls.

### Exercise 68 — Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [69]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.61262202 0.56761648 0.36664083 0.52801524 0.7230122  0.57877396
 0.42144035 0.38089822 0.41748832 0.78051775]
0    0.612622
1    0.567616
2    0.366641
3    0.528015
4    0.723012
5    0.578774
6    0.421440
7    0.380898
8    0.417488
9    0.780518
dtype: float64


**💡 Key idea:** `np.bincount(S, weights=D)` (dividing by `np.bincount(S)`) computes the group-wise average of `D`, grouped by the labels in `S` — the same idea as a pandas `groupby().mean()`, shown here for comparison.

### Exercise 69 — How to get the diagonal of a dot product? (★★★)

In [70]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.17681299, 1.4797081 , 0.60601493, 1.04053343, 0.92045776])

**💡 Key idea:** Computing the diagonal of `A @ B` the naive way wastes effort on off-diagonal entries; `np.einsum("ij,ji->i", A, B)` computes only the diagonal directly.

### Exercise 70 — Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [71]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**💡 Key idea:** Slicing with a step (`Z0[::nz+1] = Z`) inserts the original values at regular intervals into a larger array pre-filled with zeros.

### Exercise 71 — Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [72]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**💡 Key idea:** Adding a new axis with `B[:,:,None]` reshapes `B` so its shape becomes broadcastable against the 3D array `A`.

### Exercise 72 — How to swap two rows of an array? (★★★)

In [73]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**💡 Key idea:** Fancy indexing with a list of row positions (`A[[0,1]] = A[[1,0]]`) swaps two rows in a single line.

### Exercise 73 — Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [74]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 64) ( 0, 96) ( 4, 19) ( 4, 44) (19, 44) (22, 52) (22, 71) (26, 51)
 (26, 59) (40, 46) (40, 73) (43, 70) (43, 71) (46, 68) (46, 73) (46, 80)
 (47, 60) (47, 61) (51, 59) (52, 71) (60, 61) (64, 96) (68, 80) (70, 71)
 (70, 87) (73, 87) (73, 93) (87, 87) (87, 93)]


**💡 Key idea:** This builds every edge of every triangle, sorts each edge's two endpoints so direction doesn't matter, then uses `np.unique()` to drop duplicate shared edges.

### Exercise 74 — Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [75]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


**💡 Key idea:** `np.repeat()` is the inverse of `np.bincount()`: given how many times each number should appear, it rebuilds the original list of numbers.

### Exercise 75 — How to compute averages using a sliding window over an array? (★★★)

In [76]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


**💡 Key idea:** A **moving average** smooths noisy data by averaging a small sliding window of neighboring values; `sliding_window_view()` is the clean, modern way to create those windows.

### Exercise 76 — Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [77]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


**💡 Key idea:** `sliding_window_view()` (or manual `as_strided`) builds a 2D array where each row is a small overlapping 'window' shifted by one from the row before.

### Exercise 77 — How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [78]:
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.35740703,  0.0577491 ,  0.15908177, -0.11758255, -0.81738601,
        0.17501038, -0.40740526,  0.9600697 ,  0.24673135, -0.17819849,
       -0.87485376, -0.91646568, -0.86655291, -0.7332406 ,  0.3819198 ,
        0.97632608, -0.97587694,  0.21538445,  0.01713008, -0.36067481,
        0.8803429 ,  0.91899467, -0.49654   , -0.39573324,  0.45041634,
        0.02693263, -0.65715367,  0.89877228, -0.28927084, -0.4508391 ,
       -0.99510095,  0.51333723, -0.68804412,  0.48165881,  0.9837241 ,
       -0.33720077, -0.61623026, -0.05562284, -0.00303955,  0.44102951,
        0.22968727, -0.52883565,  0.53116058, -0.09114821, -0.21137447,
       -0.7637532 ,  0.07536714, -0.75989808, -0.43408644, -0.20154898,
        0.95365669,  0.1717149 ,  0.39448308,  0.74783944, -0.27104913,
        0.00517377, -0.40400819, -0.19066764,  0.22202332, -0.66403387,
       -0.45181664, -0.86066105, -0.16610484,  0.51163034,  0.5170874 ,
        0.30247343, -0.52689844, -0.72702995,  0.81508886, -0.02

**💡 Key idea:** Passing `out=Z` back into the same array (`np.logical_not(Z, out=Z)` or `np.negative(Z, out=Z)`) flips values in place, without allocating a new array.

### Exercise 78 — Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [79]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 6.20771995  4.17701927  1.34245123  6.3239317   3.43048953  2.11388826
 10.13925416  6.50298677  1.68400181  3.2680487 ]


**💡 Key idea:** Point-to-line-segment distance is a classic geometry formula, implemented here with vectorized NumPy operations instead of a manual loop over each line.

### Exercise 79 — Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [80]:
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.4797214   6.52641838  2.31527192  1.03993945  9.0425685  10.73468449
   6.23745578  5.91803308  0.32369989 10.01492962]
 [14.91463276  9.94144248  8.07850126 11.02599079 13.29771171 16.45297313
   4.37227019  6.1616811  11.7066948  15.03393104]
 [ 3.69397216  1.87211507  4.03247869  0.8890572   1.17175259  3.91739715
   4.37204962  0.97939703  6.70776174  2.6716146 ]
 [ 2.95614406  6.12166319 10.58850358  5.67254958  3.42943728  1.26024512
   6.1157396   4.26137172  1.53177238  2.23654228]
 [15.0997409   3.60424641  6.80249283 12.50767987  7.36085603 11.31491638
   3.64580901 11.3964891  17.04264814  9.49709694]
 [ 3.78480261  0.12203029  3.50550661  0.58907444  3.05356793  5.57232573
   1.92892623  0.47527358  5.22133044  4.4402124 ]
 [11.93601666  5.06384855  4.47006279  8.6855208   8.44255313 11.70025297
   0.12522763  6.15891499 11.7803746  10.22164387]
 [ 7.41113332  8.5855984   1.45815336  2.9303184  11.33704203 13.42488082
   6.7021499   2.46264189  3.1006203  12.51835078]


**💡 Key idea:** This reuses the `distance()` function from exercise 78 for every point in a set, via a Python list comprehension (Class 8, Section 2).

### Exercise 80 — Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [81]:
import numpy as np

def extract(Z, shape, position, fill=0):
    R = np.ones(shape, dtype=Z.dtype) * fill

    Z_h, Z_w = Z.shape
    R_h, R_w = shape
    y, x = position

    y1 = max(0, y - R_h // 2)
    y2 = min(Z_h, y + R_h // 2 + 1)
    x1 = max(0, x - R_w // 2)
    x2 = min(Z_w, x + R_w // 2 + 1)

    Ry1 = max(0, R_h // 2 - y)
    Rx1 = max(0, R_w // 2 - x)

    R[Ry1:Ry1 + (y2 - y1), Rx1:Rx1 + (x2 - x1)] = Z[y1:y2, x1:x2]
    return R

**💡 Key idea:** This function safely extracts a sub-window around any position, using `max()`/`min()` to clip the window at the array's edges and padding the rest with a fill value.

### Exercise 81 — Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [82]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


**💡 Key idea:** `sliding_window_view(Z, window_shape=4)` is the modern replacement for manual `as_strided` tricks — it produces every 4-element overlapping window from `Z`.

### Exercise 82 — Compute a matrix rank (★★★)

In [83]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:
# Author: Jeff Luo (@Jeff1999)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


**💡 Key idea:** `np.linalg.matrix_rank()` (or counting the significant singular values from `np.linalg.svd()`) reports how many independent rows/columns a matrix truly has.

### Exercise 84 — Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [84]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[1 2 2]
   [2 2 2]
   [1 3 2]]

  [[2 2 2]
   [2 2 3]
   [3 2 1]]

  [[2 2 3]
   [2 3 1]
   [2 1 3]]

  [[2 3 2]
   [3 1 3]
   [1 3 3]]

  [[3 2 0]
   [1 3 2]
   [3 3 1]]

  [[2 0 1]
   [3 2 0]
   [3 1 3]]

  [[0 1 1]
   [2 0 4]
   [1 3 1]]

  [[1 1 2]
   [0 4 1]
   [3 1 0]]]


 [[[2 2 2]
   [1 3 2]
   [1 3 2]]

  [[2 2 3]
   [3 2 1]
   [3 2 1]]

  [[2 3 1]
   [2 1 3]
   [2 1 0]]

  [[3 1 3]
   [1 3 3]
   [1 0 1]]

  [[1 3 2]
   [3 3 1]
   [0 1 2]]

  [[3 2 0]
   [3 1 3]
   [1 2 2]]

  [[2 0 4]
   [1 3 1]
   [2 2 1]]

  [[0 4 1]
   [3 1 0]
   [2 1 1]]]


 [[[1 3 2]
   [1 3 2]
   [3 3 1]]

  [[3 2 1]
   [3 2 1]
   [3 1 3]]

  [[2 1 3]
   [2 1 0]
   [1 3 2]]

  [[1 3 3]
   [1 0 1]
   [3 2 3]]

  [[3 3 1]
   [0 1 2]
   [2 3 2]]

  [[3 1 3]
   [1 2 2]
   [3 2 3]]

  [[1 3 1]
   [2 2 1]
   [2 3 2]]

  [[3 1 0]
   [2 1 1]
   [3 2 2]]]


 [[[1 3 2]
   [3 3 1]
   [2 4 2]]

  [[3 2 1]
   [3 1 3]
   [4 2 0]]

  [[2 1 0]
   [1 3 2]
   [2 0 2]]

  [[1 0 1]
   [3 2 3]
   [0 2 4]]

  [[0 1 2]
   

**💡 Key idea:** `sliding_window_view(Z, window_shape=(3,3))` generalizes the same sliding-window idea to two dimensions, extracting every 3×3 block from a matrix.

### Exercise 85 — Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [85]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  2  3  4 16]
 [ 2  3  3 11 16]
 [ 3  3  1 42 15]
 [ 4 11 42  8  9]
 [16 16 15  9  3]]


**💡 Key idea:** This subclasses `np.ndarray` so that setting `Z[i,j]` automatically also sets `Z[j,i]`, guaranteeing the array always stays symmetric.

### Exercise 86 — Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [86]:
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


**💡 Key idea:** `np.tensordot()` generalizes matrix multiplication to higher-dimensional arrays by specifying exactly which axes should be multiplied-and-summed together.

### Exercise 87 — Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [87]:
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

# Author: Jeff Luo (@Jeff1999)

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


**💡 Key idea:** `np.add.reduceat()` (or `sliding_window_view` with a stride) sums up non-overlapping blocks of a grid — like shrinking a 16×16 image into a 4×4 grid of block totals.

### Exercise 88 — How to implement the Game of Life using numpy arrays? (★★★)

In [88]:
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0

**💡 Key idea:** Conway's Game of Life counts each cell's living neighbors with shifted array slices, then applies the birth/survival rules to the whole grid at once — no per-cell loop needed.

### Exercise 89 — How to get the n largest values of an array (★★★)

In [89]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


**💡 Key idea:** `np.argpartition()` finds the n largest values *without* fully sorting the whole array first, which is much faster than `np.argsort()` on large arrays.

### Exercise 90 — Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [90]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**💡 Key idea:** This builds every possible combination of elements from several input lists — the Cartesian product — using `np.indices()` to generate all index combinations at once.

### Exercise 91 — How to create a record array from a regular array? (★★★)

In [91]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.rec.fromarrays(Z.T,
                       names='col1, col2, col3',
                       formats='S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


**💡 Key idea:** `np.rec.fromarrays()` converts a plain array into a **record array**, where each field can be accessed by name (like `R.col1`) instead of only by position.

### Exercise 92 — Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [92]:
# Author: Ryan G. (adapted to use the standard-library timeit module
# so this cell also runs outside Jupyter/IPython)
import timeit

x = np.random.rand(2_000_000)

t1 = timeit.timeit(lambda: np.power(x, 3), number=5)
t2 = timeit.timeit(lambda: x*x*x, number=5)
t3 = timeit.timeit(lambda: np.einsum('i,i,i->i', x, x, x), number=5)

print(f"np.power(x,3)              : {t1:.4f} sec")
print(f"x*x*x                      : {t2:.4f} sec")
print(f"np.einsum('i,i,i->i',...)  : {t3:.4f} sec")

# Note: in a real Jupyter notebook you can also just write:
#   %timeit np.power(x,3)
# The %timeit magic is more accurate (it runs many trials automatically)
# but only works inside Jupyter/IPython, not in a plain .py script.

np.power(x,3)              : 0.1737 sec
x*x*x                      : 0.0747 sec
np.einsum('i,i,i->i',...)  : 0.0478 sec


**💡 Key idea:** Comparing `np.power(x,3)`, `x*x*x`, and `np.einsum(...)` shows that for simple element-wise math, plain multiplication is often faster than calling a more general function.

### Exercise 93 — Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [93]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 4 6 7]


**💡 Key idea:** Broadcasting `A` against `B` with extra `np.newaxis` dimensions checks, for every row of `A`, whether it contains all the values from a row of `B` — regardless of order.

### Exercise 94 — Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [94]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 4 0]
 [4 2 0]
 [4 0 0]
 [4 1 0]
 [0 1 1]
 [1 4 3]
 [4 0 3]
 [2 4 3]
 [0 1 4]
 [1 2 2]]
[[2 4 0]
 [4 2 0]
 [4 0 0]
 [4 1 0]
 [0 1 1]
 [1 4 3]
 [4 0 3]
 [2 4 3]
 [0 1 4]
 [1 2 2]]
[[2 4 0]
 [4 2 0]
 [4 0 0]
 [4 1 0]
 [0 1 1]
 [1 4 3]
 [4 0 3]
 [2 4 3]
 [0 1 4]
 [1 2 2]]


**💡 Key idea:** Comparing each row to its own first column (`Z[:,1:] == Z[:,:-1]`) identifies rows where every value is identical, so they can be filtered out.

### Exercise 95 — Convert a vector of ints into a matrix binary representation (★★★)

In [95]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


**💡 Key idea:** Bitwise AND against powers of two (`2**np.arange(8)`) extracts each bit of a number one at a time, building its binary representation as a row of 0s and 1s.

### Exercise 96 — Given a two dimensional array, how to extract unique rows? (★★★)

In [96]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]


**💡 Key idea:** Viewing each row as one combined block of raw bytes lets `np.unique()` compare whole rows at once — or, more simply, `np.unique(Z, axis=0)` does this directly in modern NumPy.

### Exercise 97 — Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [97]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.0596865 , 0.17785611, 0.62796576, 0.58403048, 0.10572177,
        0.23871603, 0.19727621, 0.41095485, 0.17704238, 0.73549928],
       [0.06135828, 0.18283774, 0.64555466, 0.60038878, 0.10868296,
        0.24540231, 0.20280178, 0.42246542, 0.18200122, 0.75610012],
       [0.05234351, 0.15597518, 0.55070963, 0.51217953, 0.09271524,
        0.20934775, 0.1730061 , 0.36039671, 0.15526156, 0.64501373],
       [0.01172933, 0.0349515 , 0.12340506, 0.11477109, 0.02077597,
        0.04691142, 0.03876785, 0.08075903, 0.03479159, 0.14453707],
       [0.05178808, 0.15432009, 0.54486592, 0.50674468, 0.09173141,
        0.20712631, 0.17117029, 0.35657246, 0.15361404, 0.63816934],
       [0.07515925, 0.22396242, 0.79075566, 0.73543087, 0.13312841,
        0.30059928, 0.24841686, 0.5174882 , 0.22293774, 0.9261655 ],
       [0.05235103, 0.15599759, 0.55078874, 0.5122531 , 0.09272856,
        0.20937782, 0.17303095, 0.36044848, 0.15528386, 0.64510638],
       [0.0560309 , 0.16696301, 0.5895049

**💡 Key idea:** `np.einsum()` is a single, flexible notation that can express sum, element-wise multiply, inner product, and outer product just by changing its subscript pattern.

### Exercise 98 — Considering a path described by two vectors (X,Y), how to sample it using equidistant samples ? (★★★)

In [98]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

**💡 Key idea:** By measuring cumulative distance traveled along a path (`np.cumsum`) and using `np.interp()` to resample it, this produces evenly-spaced points along an irregular curve.

### Exercise 99 — Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [99]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


**💡 Key idea:** `np.mod(X, 1) == 0` checks that every value in a row is a whole number, and combined with a row-sum check, filters out rows that could plausibly be counts from `n` trials.

### Exercise 100 — Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [100]:
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12718499  0.26624538]


**💡 Key idea:** **Bootstrapping** estimates uncertainty by resampling the data (with replacement) thousands of times and looking at the spread of the resulting means — a widely used statistics technique.

# 🎉 You've reached the end of the 100 exercises!

## What this practice set covered

- Array creation, indexing, and slicing (reinforcing Class 9, Parts A, B, E)
- Broadcasting, arithmetic, and comparisons (Class 9, Part D)
- Reading/writing data and reshaping (Class 9, Part C)
- Many functions **beyond** Class 9's core scope: structured/record arrays, `stride_tricks`, `einsum`, date arithmetic, and a first taste of `scipy` and `pandas`

## Suggested next steps

- Re-attempt the exercises you found hardest **without** looking at the solution.
- Pick 2–3 Advanced exercises and try to explain the solution to someone else, in your own words — that is one of the best ways to confirm real understanding.
- Move on to the **NumPy → pandas** class, since pandas builds directly on everything practiced here.

---

## 👨‍💻 About This Course

This **free Python course** was designed and developed by **Muhammad Saad** as a contribution toward making programming education more accessible. I created it to share what I’ve learned with students and beginners who want to learn Python but may not have access to paid courses.

The goal is simple: **to make learning Python easier, accessible, and beginner-friendly.** If this course helps someone learn a new skill or take their first step into programming, then this initiative has achieved its purpose.

If you found this class helpful, feel free to share it with someone who might benefit from it.

*The 100 NumPy exercises in this notebook are adapted from the open-source [numpy-100](https://github.com/rougier/numpy-100) project by Nicolas P. Rougier and contributors.*