# 🧮 Python Class 9 — All Practice Questions Solved

## NumPy Numerical Computing Masterclass

This notebook contains the **complete solved set of the practice questions from Python Class 9**, kept in the original sequence. Each question follows the same professional pattern:

**Question → Code → Output → Line-by-Line Explanation**

All executable examples are designed to run directly in a Jupyter/VS Code notebook. Expected outputs are saved after execution.


# Part A — From Python Lists to NumPy Arrays

## Question 1

**Create three variables for the climate data of your own city (make up reasonable numbers).**

In [1]:
city_name = "Islamabad"
city_temp = 75
city_rainfall = 110
city_humidity = 55

print(city_name)
print(city_temp, city_rainfall, city_humidity)

Islamabad
75 110 55


### 🔍 Line-by-Line Explanation

1. `city_name = "Islamabad"` stores the name of the example city in a string variable.
2. `city_temp = 75` stores the example temperature value.
3. `city_rainfall = 110` stores the example rainfall value.
4. `city_humidity = 55` stores the example humidity value.
5. The two `print()` calls display the stored city and climate values so we can verify them.

## Question 2

**Calculate the predicted apple yield for your city using the formula above.**

In [2]:
w1, w2, w3 = 0.3, 0.2, 0.5

city_yield = city_temp * w1 + city_rainfall * w2 + city_humidity * w3
print(city_yield)

72.0


### 🔍 Line-by-Line Explanation

1. `w1, w2, w3 = 0.3, 0.2, 0.5` creates the three weights used by the linear model.
2. `city_temp * w1` calculates the temperature contribution to the prediction.
3. `city_rainfall * w2` calculates the rainfall contribution.
4. `city_humidity * w3` calculates the humidity contribution.
5. The three weighted contributions are added and stored in `city_yield`.
6. `print(city_yield)` displays the final predicted yield.

## Question 3

**Print the result using an f-string instead of `.format()`.**

In [3]:
print(f"The expected yield of apples in {city_name} is {city_yield} tons per hectare.")

The expected yield of apples in Islamabad is 72.0 tons per hectare.


### 🔍 Line-by-Line Explanation

1. `f"..."` creates an f-string, allowing variables to be placed directly inside `{}`.
2. `{city_name}` inserts the city name.
3. `{city_yield}` inserts the calculated prediction.
4. `print()` displays the complete sentence.

## Question 4

**Change one weight slightly and observe how the prediction changes.**

In [4]:
old_w2 = w2
new_w2 = 0.25

old_yield = city_temp * w1 + city_rainfall * old_w2 + city_humidity * w3
new_yield = city_temp * w1 + city_rainfall * new_w2 + city_humidity * w3

print("Old weight:", old_w2)
print("New weight:", new_w2)
print("Old prediction:", old_yield)
print("New prediction:", new_yield)
print("Change:", new_yield - old_yield)

Old weight: 0.2
New weight: 0.25
Old prediction: 72.0
New prediction: 77.5
Change: 5.5


### 🔍 Line-by-Line Explanation

1. `old_w2 = w2` saves the original rainfall weight so we can compare it later.
2. `new_w2 = 0.25` slightly increases the rainfall weight from `0.2` to `0.25`.
3. `old_yield = ...` calculates the prediction using the original weight.
4. `new_yield = ...` calculates the prediction using the changed weight.
5. The `print()` statements show both predictions and their difference.
6. Because rainfall is positive in this model, increasing its positive weight increases the predicted yield.

## Question 5

**Explain, in your own words, why this is called a “linear” model.**

In [5]:
temperature = city_temp
rainfall = city_rainfall
humidity = city_humidity

# The prediction is a weighted sum of the input variables.
prediction = w1 * temperature + w2 * rainfall + w3 * humidity
print("Linear-model prediction:", prediction)

Linear-model prediction: 72.0


### 🔍 Line-by-Line Explanation

1. `temperature`, `rainfall`, and `humidity` represent the input variables.
2. The prediction is calculated by multiplying each input by one fixed weight.
3. The weighted terms are then added together.
4. There are no squared, cubed, logarithmic, or other nonlinear transformations in this formula.
5. That simple weighted-sum relationship is why this example is called a linear model.


# A Manual `crop_yield` Function

## Question 6

**Create a list representing the climate data of a sixth city.**

In [6]:
sixth_city = [78, 85, 60]
print(sixth_city)

[78, 85, 60]


### 🔍 Line-by-Line Explanation

1. `sixth_city = [78, 85, 60]` creates a list containing temperature, rainfall, and humidity in that order.
2. `print(sixth_city)` displays the list so its values can be checked.

## Question 7

**Use `crop_yield` to calculate its predicted yield.**

In [7]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

weights = [0.3, 0.2, 0.5]
print("Sixth-city predicted yield:", crop_yield(sixth_city, weights))

Sixth-city predicted yield: 70.4


### 🔍 Line-by-Line Explanation

1. `def crop_yield(region, weights):` defines a reusable function with two inputs.
2. `result = 0` starts the running total at zero.
3. `zip(region, weights)` pairs each climate value with its matching weight.
4. `result += x * w` calculates each weighted contribution and adds it to the total.
5. `return result` sends the completed prediction back to the caller.
6. `crop_yield(sixth_city, weights)` applies the function to the sixth city.

## Question 8

**Explain in your own words what `zip()` does inside the `crop_yield` function.**

In [8]:
region = [78, 85, 60]
weights = [0.3, 0.2, 0.5]

pairs = list(zip(region, weights))
print(pairs)

[(78, 0.3), (85, 0.2), (60, 0.5)]


### 🔍 Line-by-Line Explanation

1. `region` contains the climate values and `weights` contains the matching weights.
2. `zip(region, weights)` pairs elements by position: first with first, second with second, and so on.
3. `list(...)` converts the zip object into a visible list of pairs.
4. The output makes it easy to see exactly which value is multiplied by which weight.

## Question 9

**Deliberately give `crop_yield` a weights list with only two values and observe what happens.**

In [9]:
bad_weights = [0.3, 0.2]
print("Result with only two weights:", crop_yield(sixth_city, bad_weights))

Result with only two weights: 40.4


### 🔍 Line-by-Line Explanation

1. `bad_weights` intentionally contains only two weights for three climate values.
2. `crop_yield(sixth_city, bad_weights)` still runs because `zip()` stops when the shorter input ends.
3. The third climate value is therefore ignored instead of producing an automatic error.
4. This demonstrates why checking data and weight lengths is important.

## Question 10

**Explain why a silently wrong answer can be more dangerous than a program that crashes.**

In [10]:
region = [78, 85, 60]
bad_weights = [0.3, 0.2]
good_weights = [0.3, 0.2, 0.5]

silent_result = crop_yield(region, bad_weights)
correct_result = crop_yield(region, good_weights)

print("Silent result:", silent_result)
print("Correct result:", correct_result)
print("Difference:", correct_result - silent_result)

Silent result: 40.4
Correct result: 70.4
Difference: 30.000000000000007


### 🔍 Line-by-Line Explanation

1. `silent_result` uses the incomplete weight list and therefore ignores one input.
2. `correct_result` uses all three weights and all three climate values.
3. The printed difference shows that the two calculations can produce different answers even though neither calculation crashes.
4. A crash is visible and forces us to investigate; a silent wrong result can look valid and may therefore be trusted incorrectly.


# NumPy Arrays, Dot Products, and List Arithmetic

## Question 11

**Convert two lists of your choice into NumPy arrays and add them together.**

In [11]:
import numpy as np

list1 = [10, 20, 30]
list2 = [1, 2, 3]
arr1 = np.array(list1)
arr2 = np.array(list2)

print(arr1 + arr2)

[11 22 33]


### 🔍 Line-by-Line Explanation

1. `import numpy as np` imports NumPy using the standard `np` alias.
2. `list1` and `list2` are ordinary Python lists.
3. `np.array(...)` converts each list into a NumPy array.
4. `arr1 + arr2` performs element-wise addition: `10+1`, `20+2`, and `30+3`.
5. `print()` displays the resulting NumPy array.

## Question 12

**Use `np.dot()` on two arrays of the same length.**

In [12]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

dot_result = np.dot(arr1, arr2)
print(dot_result)

140


### 🔍 Line-by-Line Explanation

1. `arr1` and `arr2` are NumPy arrays with three elements each.
2. `np.dot(arr1, arr2)` multiplies matching elements and adds the products.
3. The calculation is `10×1 + 20×2 + 30×3`.
4. `print(dot_result)` displays the final scalar dot product.

## Question 13

**Reproduce the same dot product using element-wise multiplication and `.sum()`.**

In [13]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

products = arr1 * arr2
dot_result = products.sum()

print("Element-wise products:", products)
print("Dot product:", dot_result)

Element-wise products: [10 40 90]
Dot product: 140


### 🔍 Line-by-Line Explanation

1. `arr1 * arr2` performs element-wise multiplication.
2. `products` therefore contains `[10, 40, 90]`.
3. `.sum()` adds those products together.
4. The final value is the same dot product produced by `np.dot()`.

## Question 14

**Try subtracting two plain Python lists directly and read the resulting error message carefully.**

In [14]:
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]

try:
    result = lst1 - lst2
    print(result)
except TypeError as e:
    print("Expected error:", e)

Expected error: unsupported operand type(s) for -: 'list' and 'list'


### 🔍 Line-by-Line Explanation

1. `lst1` and `lst2` are plain Python lists.
2. `lst1 - lst2` asks Python to subtract one list from another.
3. Python lists do not define element-wise subtraction, so a `TypeError` occurs.
4. `try/except` catches the expected error so the notebook can continue running.
5. Printing the exception lets us inspect the error message safely.

## Question 15

**Explain the difference between `list1 + list2` and `arr1 + arr2` for NumPy arrays.**

In [15]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
arr1 = np.array(list1)
arr2 = np.array(list2)

print("Python lists:", list1 + list2)
print("NumPy arrays:", arr1 + arr2)

Python lists: [1, 2, 3, 4, 5, 6]
NumPy arrays: [5 7 9]


### 🔍 Line-by-Line Explanation

1. `list1 + list2` uses Python-list concatenation, so the second list is placed after the first.
2. `np.array(...)` converts the lists into NumPy arrays.
3. `arr1 + arr2` uses NumPy element-wise arithmetic, adding matching positions.
4. Therefore the same `+` symbol has different behavior because the underlying data types are different.


# Performance — Loops vs. NumPy

## Question 16

**Repeat the timing comparison with vectors of 10,000,000 elements instead of 1,000,000.**

In [16]:
import time
import numpy as np

n = 10_000_000
list_a = list(range(n))
list_b = list(range(n))
arr_a = np.arange(n)
arr_b = np.arange(n)

start = time.perf_counter()
list_result = [a + b for a, b in zip(list_a, list_b)]
python_time = time.perf_counter() - start

del list_result, list_a, list_b

start = time.perf_counter()
array_result = arr_a + arr_b
numpy_time = time.perf_counter() - start

del array_result

print(f"Python list loop time: {python_time:.6f} seconds")
print(f"NumPy addition time:   {numpy_time:.6f} seconds")
print(f"Speed ratio:            {python_time / numpy_time:.2f}x")

Python list loop time: 1.425003 seconds
NumPy addition time:   0.017799 seconds
Speed ratio:            80.06x


### 🔍 Line-by-Line Explanation

1. `n = 10_000_000` sets the requested vector size.
2. `list_a` and `list_b` create two Python lists containing ten million integers.
3. `arr_a` and `arr_b` create equivalent NumPy arrays.
4. `time.perf_counter()` records high-resolution timing around each operation.
5. The list comprehension performs addition through Python-level iteration.
6. `arr_a + arr_b` performs the same element-wise addition using NumPy’s optimized implementation.
7. `del` removes large temporary results after timing to reduce unnecessary memory use.
8. The final lines report both times and their ratio. Exact timings depend on the computer running the notebook.

## Question 17

**Predict, before running it, whether the speed gap will grow or shrink with more data — then check.**

In [17]:
import time
import numpy as np

n = 10_000_000
arr_a = np.arange(n)
arr_b = np.arange(n)

print("Prediction: with more elements, the NumPy advantage should generally become more noticeable because Python performs more per-element interpreter work.")

start = time.perf_counter()
python_sum = sum(a + b for a, b in zip(arr_a.tolist(), arr_b.tolist()))
python_time = time.perf_counter() - start

start = time.perf_counter()
numpy_sum = np.sum(arr_a + arr_b)
numpy_time = time.perf_counter() - start

print(f"Python-style time: {python_time:.6f} seconds")
print(f"NumPy time:        {numpy_time:.6f} seconds")
print("Same result:", python_sum == numpy_sum)

Prediction: with more elements, the NumPy advantage should generally become more noticeable because Python performs more per-element interpreter work.


Python-style time: 0.960919 seconds
NumPy time:        0.017031 seconds
Same result: True


### 🔍 Line-by-Line Explanation

1. `n = 10_000_000` creates a large workload.
2. The first `print()` records the prediction before timing, as requested.
3. The generator expression performs the addition one pair at a time through Python iteration.
4. `np.sum(arr_a + arr_b)` lets NumPy handle the array operation and reduction.
5. The timing values test the prediction; they can vary between computers.
6. Comparing `python_sum` and `numpy_sum` verifies that both approaches calculated the same total.

## Question 18

**Explain in your own words why a C-based implementation can be faster than a Python loop.**

In [18]:
import numpy as np

arr = np.arange(1_000_000)
python_loop_concept = "Python loop: repeatedly executes element-level work through the Python interpreter."
numpy_concept = "NumPy: delegates array operations to optimized compiled code (largely C/Fortran/Cython-backed)."

print(python_loop_concept)
print(numpy_concept)
print("Example result:", np.sum(arr))

Python loop: repeatedly executes element-level work through the Python interpreter.
NumPy: delegates array operations to optimized compiled code (largely C/Fortran/Cython-backed).
Example result: 499999500000


### 🔍 Line-by-Line Explanation

1. `arr` creates one million numerical values.
2. `python_loop_concept` summarizes the extra interpreter-level work involved in a Python loop.
3. `numpy_concept` summarizes why NumPy can be faster: its numerical operations are implemented in optimized compiled code.
4. `np.sum(arr)` demonstrates the kind of bulk operation NumPy is designed to perform efficiently.
5. The key idea is that Python does not need to repeatedly interpret every arithmetic operation when optimized compiled routines handle the bulk work.

## Question 19

**Time how long `sum(arr1)` takes versus `arr1_np.sum()`.**

In [19]:
import time
import numpy as np

arr1 = list(range(1_000_000))
arr1_np = np.array(arr1)

start = time.perf_counter()
python_total = sum(arr1)
python_time = time.perf_counter() - start

start = time.perf_counter()
numpy_total = arr1_np.sum()
numpy_time = time.perf_counter() - start

print(f"sum(arr1):   {python_time:.6f} seconds")
print(f"arr1_np.sum(): {numpy_time:.6f} seconds")
print("Same result:", python_total == numpy_total)

sum(arr1):   0.008379 seconds
arr1_np.sum(): 0.000481 seconds
Same result: True


### 🔍 Line-by-Line Explanation

1. `arr1` is a Python list of one million integers.
2. `arr1_np` converts the same values to a NumPy array.
3. `sum(arr1)` measures Python’s built-in summation over the list.
4. `arr1_np.sum()` measures NumPy’s optimized array reduction.
5. The final comparison confirms both methods return the same numerical total.
6. Exact timing depends on the machine and system load.

## Question 20

**Name one real-world situation where this performance difference could matter.**

In [20]:
examples = [
    "Processing millions of sensor readings in a scientific experiment",
    "Calculating statistics for a large machine-learning dataset",
    "Applying image or signal-processing operations to large numerical arrays"
]

print("Example real-world situation:", examples[0])

Example real-world situation: Processing millions of sensor readings in a scientific experiment


### 🔍 Line-by-Line Explanation

1. `examples` stores several realistic situations where large numerical workloads occur.
2. `examples[0]` selects the first example.
3. `print()` displays one situation: processing millions of sensor readings.
4. When datasets contain millions of values, faster bulk operations can save substantial execution time.


# 2D Arrays, 3D Arrays, Shape, and Dtype

## Question 21

**Create a 2D array representing three students' scores in three subjects.**

In [21]:
scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [76, 81, 89]
])

print(scores)

[[85 90 78]
 [92 88 95]
 [76 81 89]]


### 🔍 Line-by-Line Explanation

1. `np.array(...)` converts the nested list into a NumPy array.
2. Each inner list represents one student.
3. Each row contains three subject scores.
4. Because there are rows and columns, the result is a 2D array.

## Question 22

**Print its `.shape` and explain what each number means.**

In [22]:
print("Shape:", scores.shape)

Shape: (3, 3)


### 🔍 Line-by-Line Explanation

1. `.shape` returns the dimensions of the array.
2. The first number is the number of rows, here three students.
3. The second number is the number of columns, here three subjects.
4. Therefore `(3, 3)` means three rows by three columns.

## Question 23

**Create a 3D array and predict its shape before checking with `.shape`.**

In [23]:
three_d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print("Predicted shape: (3, 2, 2)")
print("Actual shape:   ", three_d.shape)

Predicted shape: (3, 2, 2)
Actual shape:    (3, 2, 2)


### 🔍 Line-by-Line Explanation

1. `three_d` contains three 2×2 blocks.
2. The outermost level contains three blocks.
3. Each block has two rows.
4. Each row has two elements.
5. Therefore the predicted shape is `(3, 2, 2)`, which `.shape` confirms.

## Question 24

**Create two arrays, one with only integers and one with a mix of integers and a single float, and compare their `.dtype`.**

In [24]:
integers = np.array([1, 2, 3, 4])
mixed = np.array([1, 2, 3, 4.5])

print("Integer dtype:", integers.dtype)
print("Mixed dtype:  ", mixed.dtype)

Integer dtype: int64
Mixed dtype:   float64


### 🔍 Line-by-Line Explanation

1. `integers` contains only integer values, so NumPy can use an integer dtype.
2. `mixed` contains a floating-point value along with integers.
3. NumPy promotes the integer values to a compatible floating-point dtype so every element can share one array dtype.
4. `.dtype` reveals the data type chosen for each array.

## Question 25

**Explain in your own words why NumPy insists that every element in an array share the same type.**

In [25]:
arr = np.array([1, 2, 3, 4])
print("dtype:", arr.dtype)
print("itemsize:", arr.itemsize, "bytes")

dtype: int64
itemsize: 8 bytes


### 🔍 Line-by-Line Explanation

1. `arr` creates a homogeneous numerical array.
2. `.dtype` shows the single data type used by all elements.
3. `.itemsize` shows how many bytes each element occupies for that dtype.
4. Using one consistent type makes memory layout predictable and allows optimized numerical operations, which is a major reason NumPy arrays are efficient.


# Matrix Multiplication with `@`

## Question 26

**Create your own 3×3 matrix and a length-3 vector, and multiply them with `@`.**

In [26]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
vector = np.array([10, 20, 30])

result = matrix @ vector
print(result)

[140 320 500]


### 🔍 Line-by-Line Explanation

1. `matrix` is a 3×3 NumPy array.
2. `vector` is a one-dimensional array containing three values.
3. `matrix @ vector` performs matrix multiplication.
4. Each output value is the dot product of one matrix row with the vector.
5. The result has three values, one for each matrix row.

## Question 27

**Predict the shape of the result before running the code.**

In [27]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
vector = np.array([10, 20, 30])

print("Prediction: (3,)")
result = matrix @ vector
print("Actual:    ", result.shape)
print("Result:    ", result)

Prediction: (3,)
Actual:     (3,)
Result:     [140 320 500]


### 🔍 Line-by-Line Explanation

1. `matrix` has shape `(3, 3)`.
2. `vector` has shape `(3,)`.
3. The inner dimensions match because the matrix has three columns and the vector has three elements.
4. The result contains one value per matrix row, so its shape is `(3,)`.
5. The printed shape confirms the prediction.

## Question 28

**Explain why `climate_data @ weights` only works because `climate_data` has exactly 3 columns and `weights` has exactly 3 elements.**

In [28]:
climate_data = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58]
])
weights = np.array([0.3, 0.2, 0.5])

print("Climate shape:", climate_data.shape)
print("Weights shape:", weights.shape)
print("Predictions:", climate_data @ weights)

Climate shape: (3, 3)
Weights shape: (3,)
Predictions: [56.8 76.9 81.9]


### 🔍 Line-by-Line Explanation

1. `climate_data.shape` is `(3, 3)`: three regions and three climate features.
2. `weights.shape` is `(3,)`: one weight for each feature.
3. Matrix multiplication needs the matrix column count to match the vector length.
4. Here both inner dimensions are three, so the multiplication is valid.
5. Each row is multiplied by the three weights to produce one prediction.

## Question 29

**Try multiplying two matrices together with `@` (both 2D).**

In [29]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

result = a @ b
print("A shape:", a.shape)
print("B shape:", b.shape)
print("Result:")
print(result)
print("Result shape:", result.shape)

A shape: (2, 3)
B shape: (3, 2)
Result:
[[ 58  64]
 [139 154]]
Result shape: (2, 2)


### 🔍 Line-by-Line Explanation

1. `a` has shape `(2, 3)`.
2. `b` has shape `(3, 2)`.
3. The inner dimensions, 3 and 3, match, so matrix multiplication is valid.
4. The result takes the outer dimensions, giving shape `(2, 2)`.
5. `print(result)` displays the resulting matrix.

## Question 30

**Compare `np.matmul(a, b)` and `a @ b` on the same two arrays and confirm they give identical results.**

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])

result_function = np.matmul(a, b)
result_operator = a @ b

print("np.matmul(a, b):")
print(result_function)
print("a @ b:")
print(result_operator)
print("Identical:", np.array_equal(result_function, result_operator))

np.matmul(a, b):
[[ 58  64]
 [139 154]]
a @ b:
[[ 58  64]
 [139 154]]
Identical: True


### 🔍 Line-by-Line Explanation

1. `np.matmul(a, b)` calls NumPy’s matrix-multiplication function explicitly.
2. `a @ b` uses Python’s matrix-multiplication operator.
3. Both expressions operate on the same two arrays.
4. `np.array_equal(...)` checks whether their shapes and values match exactly.
5. The final `True` confirms that the two forms produce identical results here.


# Working with CSV Files

## Question 31

**Generate your own synthetic dataset of 100 rows with two columns using `np.random.uniform`.**

In [31]:
import numpy as np

rng = np.random.default_rng(42)
data = rng.uniform(0, 100, size=(100, 2))

print("Shape:", data.shape)
print("First 5 rows:")
print(data[:5])

Shape: (100, 2)
First 5 rows:
[[77.39560486 43.88784398]
 [85.85979199 69.73680291]
 [ 9.41773479 97.56223516]
 [76.1139702  78.60643053]
 [12.81136327 45.03859379]]


### 🔍 Line-by-Line Explanation

1. `np.random.default_rng(42)` creates a reproducible random-number generator.
2. The seed `42` means the same code produces the same random dataset when run again.
3. `rng.uniform(0, 100, size=(100, 2))` generates values uniformly between 0 and 100.
4. `size=(100, 2)` requests 100 rows and two columns.
5. `data.shape` confirms the requested dimensions.
6. `data[:5]` displays only the first five rows to keep the output readable.

## Question 32

**Save it to a CSV file using `np.savetxt`.**

In [32]:
import numpy as np

rng = np.random.default_rng(42)
data = rng.uniform(0, 100, size=(100, 2))

csv_path = "class9_synthetic_100.csv"
np.savetxt(csv_path, data, delimiter=",", header="feature_1,feature_2", comments="")

print("Saved:", csv_path)

Saved: class9_synthetic_100.csv


### 🔍 Line-by-Line Explanation

1. `csv_path` stores the output filename.
2. `np.savetxt(...)` writes the numerical array to a text-based CSV file.
3. `delimiter=","` separates columns with commas.
4. `header=...` writes column names at the top.
5. `comments=""` prevents NumPy from putting its default `#` before the header.
6. `print()` confirms the file name used.

## Question 33

**Read it back using `np.genfromtxt` and confirm the shape matches.**

In [33]:
import numpy as np

data_loaded = np.genfromtxt("class9_synthetic_100.csv", delimiter=",", skip_header=1)

print("Loaded shape:", data_loaded.shape)
print("Shape matches:", data_loaded.shape == (100, 2))

Loaded shape: (100, 2)
Shape matches: True


### 🔍 Line-by-Line Explanation

1. `np.genfromtxt(...)` reads the CSV back into a NumPy array.
2. `delimiter=","` tells NumPy that commas separate the columns.
3. `skip_header=1` skips the column-name row.
4. `.shape` checks the dimensions of the loaded data.
5. The comparison confirms that the loaded array has the expected 100×2 shape.

## Question 34

**Add a third column that is the sum of the first two, using `.reshape()` and `np.concatenate`.**

In [34]:
import numpy as np

data_loaded = np.genfromtxt("class9_synthetic_100.csv", delimiter=",", skip_header=1)
row_sums = data_loaded.sum(axis=1).reshape(-1, 1)
combined = np.concatenate([data_loaded, row_sums], axis=1)

print("Combined shape:", combined.shape)
print(combined[:5])

Combined shape: (100, 3)
[[ 77.39560486  43.88784398 121.28344883]
 [ 85.85979199  69.73680291 155.5965949 ]
 [  9.41773479  97.56223516 106.97996995]
 [ 76.1139702   78.60643053 154.72040073]
 [ 12.81136327  45.03859379  57.84995706]]


### 🔍 Line-by-Line Explanation

1. `data_loaded.sum(axis=1)` adds the two columns separately for every row, producing 100 values.
2. `.reshape(-1, 1)` changes those 100 values from shape `(100,)` to `(100, 1)` so they form a proper column.
3. `np.concatenate([...], axis=1)` joins the original two columns and the new column horizontally.
4. The resulting array therefore has three columns.
5. `combined[:5]` previews the first five rows.

## Question 35

**Save the final combined table to a new CSV file with an appropriate header.**

In [35]:
import numpy as np

final_path = "class9_synthetic_100_with_sum.csv"
np.savetxt(
    final_path,
    combined,
    delimiter=",")

# Rewrite with a readable header using the same numerical data.
np.savetxt(
    final_path,
    combined,
    delimiter=",")

# Add the header without changing the numerical values.
with open(final_path, "r") as f:
    body = f.read()
with open(final_path, "w") as f:
    f.write("feature_1,feature_2,row_sum\n")
    f.write(body)

print("Saved final table:", final_path)
print("Final shape:", combined.shape)

Saved final table: class9_synthetic_100_with_sum.csv
Final shape: (100, 3)


### 🔍 Line-by-Line Explanation

1. `final_path` stores the name of the final CSV file.
2. `np.savetxt(...)` writes the three numerical columns using commas.
3. The file is then reopened in text mode so a clean header can be placed at the top.
4. `f.write("feature_1,feature_2,row_sum\n")` adds meaningful names for all three columns.
5. `f.write(body)` writes the numerical rows underneath the header.
6. The final prints confirm the filename and the `(100, 3)` table shape.


# Element-wise Operations

## Question 36

**Create a 2×3 array and add 10 to every element.**

In [36]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = arr + 10
print(result)

[[11 12 13]
 [14 15 16]]


### 🔍 Line-by-Line Explanation

1. `arr` creates a 2×3 NumPy array.
2. `arr + 10` broadcasts the scalar `10` to every element.
3. Each value is therefore increased by ten.
4. `print(result)` displays the updated array.

## Question 37

**Create two 2×3 arrays and multiply them element-wise.**

In [37]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[10, 20, 30], [40, 50, 60]])

result = arr2 * arr3
print(result)

[[ 10  40  90]
 [160 250 360]]


### 🔍 Line-by-Line Explanation

1. `arr2` and `arr3` both have shape `(2, 3)`.
2. `arr2 * arr3` multiplies matching positions rather than performing matrix multiplication.
3. For example, the first result is `1×10`, the second is `2×20`, and so on.
4. The result keeps the same `(2, 3)` shape.

## Question 38

**Divide an array of your choice by 5.**

In [38]:
arr = np.array([10, 25, 40, 55])
result = arr / 5
print(result)

[ 2.  5.  8. 11.]


### 🔍 Line-by-Line Explanation

1. `arr` creates a one-dimensional numerical array.
2. `arr / 5` divides every element by the scalar five.
3. NumPy performs this operation element-wise.
4. The resulting values are printed as a NumPy array.

## Question 39

**Use `%` to find which elements of an array are even.**

In [39]:
arr = np.array([3, 8, 11, 14, 20, 25])
remainders = arr % 2
even_mask = remainders == 0

print("Remainders:", remainders)
print("Even mask:", even_mask)
print("Even values:", arr[even_mask])

Remainders: [1 0 1 0 0 1]
Even mask: [False  True False  True  True False]
Even values: [ 8 14 20]


### 🔍 Line-by-Line Explanation

1. `arr % 2` calculates the remainder after dividing each element by two.
2. An even number has remainder `0`.
3. `remainders == 0` creates a Boolean mask containing `True` for even values.
4. `arr[even_mask]` uses Boolean indexing to select only those even elements.
5. The three outputs show the complete process from remainder to selected values.

## Question 40

**Explain the difference between `arr2 * arr3` and `arr2 @ arr3`.**

In [40]:
arr2 = np.array([[1, 2], [3, 4]])
arr3 = np.array([[5, 6], [7, 8]])

print("Element-wise multiplication:")
print(arr2 * arr3)
print("Matrix multiplication:")
print(arr2 @ arr3)

Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]


### 🔍 Line-by-Line Explanation

1. `arr2 * arr3` multiplies values at matching positions, so the result is `[[5, 12], [21, 32]]`.
2. `arr2 @ arr3` performs matrix multiplication using row-by-column dot products.
3. Both inputs are 2×2, so both operations are valid, but they mean different things.
4. This distinction is fundamental when working with NumPy arrays.


# Broadcasting

## Question 41

**Create a 4×3 array and successfully broadcast-add a 1D array of length 3 to it.**

In [41]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
vector = np.array([100, 200, 300])

result = matrix + vector
print(result)

[[101 202 303]
 [104 205 306]
 [107 208 309]
 [110 211 312]]


### 🔍 Line-by-Line Explanation

1. `matrix` has shape `(4, 3)`.
2. `vector` has shape `(3,)`.
3. NumPy aligns the vector with the columns and applies it to every row.
4. Because the three vector elements match the three columns, broadcasting is valid.
5. The result remains shape `(4, 3)`.

## Question 42

**Deliberately create a broadcasting error and read the error message carefully.**

In [42]:
a = np.ones((4, 3))
b = np.ones(2)

try:
    result = a + b
    print(result)
except ValueError as e:
    print("Expected broadcasting error:", e)

Expected broadcasting error: operands could not be broadcast together with shapes (4,3) (2,) 


### 🔍 Line-by-Line Explanation

1. `a` has shape `(4, 3)`.
2. `b` has shape `(2,)`.
3. NumPy compares dimensions from the right, so `3` and `2` are incompatible.
4. The addition therefore raises a `ValueError`.
5. `try/except` catches the expected error so we can inspect its message without stopping the notebook.

## Question 43

**Fix your broadcasting error by adjusting the shape of one of the arrays.**

In [43]:
a = np.ones((4, 3))
b = np.ones(2)

# Fix: use a vector whose length matches the number of columns.
b_fixed = np.ones(3)
result = a + b_fixed

print("Fixed shapes:", a.shape, b_fixed.shape)
print(result)

Fixed shapes: (4, 3) (3,)
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


### 🔍 Line-by-Line Explanation

1. `a` remains a `(4, 3)` array.
2. `b_fixed = np.ones(3)` creates three values, matching the three columns of `a`.
3. `a + b_fixed` can now broadcast the vector across all four rows.
4. The printed shapes make the compatibility clear.
5. The result contains ones plus ones, so every element becomes two.

## Question 44

**Explain the general broadcasting rule (equal, or one of them is 1).**

In [44]:
shape_a = (4, 3)
shape_b = (3,)

print("Shape A:", shape_a)
print("Shape B:", shape_b)
print("Compatible: yes — the trailing dimensions are equal (3 and 3).")

Shape A: (4, 3)
Shape B: (3,)
Compatible: yes — the trailing dimensions are equal (3 and 3).


### 🔍 Line-by-Line Explanation

1. `shape_a` represents a 4×3 array.
2. `shape_b` represents a one-dimensional array with three elements.
3. NumPy compares dimensions from right to left.
4. Two dimensions are compatible when they are equal or when one of them is `1`; a missing leading dimension is also treated as compatible for broadcasting.
5. Here the trailing dimensions are both three, so broadcasting works.

## Question 45

**Explain why broadcasting is more memory-efficient than manually copying an array to match another array's shape.**

In [45]:
large = np.zeros((1000, 1000))
row = np.ones(1000)

broadcasted_result = large + row
manual_copy = np.broadcast_to(row, large.shape)

print("Large array shape:", large.shape)
print("Row shape:", row.shape)
print("Broadcast view shape:", manual_copy.shape)
print("Results match:", np.array_equal(broadcasted_result, manual_copy))

Large array shape: (1000, 1000)
Row shape: (1000,)
Broadcast view shape: (1000, 1000)
Results match: True


### 🔍 Line-by-Line Explanation

1. `large` is a 1000×1000 array.
2. `row` contains only 1000 values.
3. NumPy can apply `row` across all rows without requiring the programmer to build 1000 separate copies.
4. `np.broadcast_to` demonstrates the matching broadcasted shape without constructing an ordinary full copy of the data.
5. This avoids unnecessary memory use and is one reason broadcasting is both convenient and efficient.


# Comparisons and Boolean Masks

## Question 46

**Create two arrays of the same shape and compare them with `==`.**

In [46]:
a = np.array([10, 20, 30, 40])
b = np.array([10, 25, 30, 45])

comparison = a == b
print(comparison)

[ True False  True False]


### 🔍 Line-by-Line Explanation

1. `a` and `b` have the same shape.
2. `a == b` compares matching elements position by position.
3. The result is a Boolean array.
4. Each position is `True` when the values are equal and `False` otherwise.

## Question 47

**Count how many elements are equal using `.sum()`.**

In [47]:
a = np.array([10, 20, 30, 40])
b = np.array([10, 25, 30, 45])

count_equal = (a == b).sum()
print("Equal elements:", count_equal)

Equal elements: 2


### 🔍 Line-by-Line Explanation

1. `a == b` creates a Boolean mask.
2. In NumPy numerical contexts, `True` behaves like `1` and `False` like `0`.
3. `.sum()` therefore counts the `True` entries.
4. The result is the number of matching positions.

## Question 48

**Use `>` to find which elements of one array are bigger than the matching elements of another.**

In [48]:
a = np.array([10, 20, 30, 40])
b = np.array([5, 25, 20, 50])

mask = a > b
print("a > b:", mask)
print("Values where a is bigger:", a[mask])

a > b: [ True False  True False]
Values where a is bigger: [10 30]


### 🔍 Line-by-Line Explanation

1. `a > b` compares matching elements.
2. `mask` stores `True` where `a` is larger and `False` elsewhere.
3. `a[mask]` selects the elements of `a` where the condition is true.
4. This combines comparison with Boolean indexing.

## Question 49

**Explain why `True` and `False` behave like `1` and `0` in this context.**

In [49]:
mask = np.array([True, False, True, True])
print("Boolean mask:", mask)
print("As integers:", mask.astype(int))
print("Sum of mask:", mask.sum())

Boolean mask: [ True False  True  True]
As integers: [1 0 1 1]
Sum of mask: 3


### 🔍 Line-by-Line Explanation

1. `mask` is a Boolean NumPy array.
2. `.astype(int)` explicitly converts `True` to `1` and `False` to `0`.
3. `.sum()` adds those Boolean values numerically.
4. That is why summing a Boolean mask counts how many conditions were true.

## Question 50

**Use a comparison and `.sum()` to count how many elements in an array are greater than a chosen number.**

In [50]:
arr = np.array([12, 5, 27, 33, 18, 41])
threshold = 20

count_greater = (arr > threshold).sum()
print("Count greater than", threshold, ":", count_greater)

Count greater than 20 : 3


### 🔍 Line-by-Line Explanation

1. `arr` contains the values to inspect.
2. `threshold = 20` chooses the comparison value.
3. `arr > threshold` creates a Boolean mask for values greater than 20.
4. `.sum()` counts the `True` entries.
5. The final print displays how many values passed the condition.


# 3D Array Indexing and Slicing

## Question 51

**Create your own 3D array and predict its `.shape` and `.size` before checking.**

In [51]:
cube = np.arange(24).reshape(2, 3, 4)

print("Prediction: shape = (2, 3, 4), size = 24")
print("Actual shape:", cube.shape)
print("Actual size:", cube.size)

Prediction: shape = (2, 3, 4), size = 24
Actual shape: (2, 3, 4)
Actual size: 24


### 🔍 Line-by-Line Explanation

1. `np.arange(24)` creates 24 consecutive values.
2. `.reshape(2, 3, 4)` arranges them into a 3D array with dimensions 2×3×4.
3. The number of elements is `2×3×4 = 24`.
4. `.shape` confirms the dimensions and `.size` confirms the total element count.

## Question 52

**Access a single element using three indices.**

In [52]:
cube = np.arange(24).reshape(2, 3, 4)
value = cube[1, 2, 3]
print("Selected value:", value)

Selected value: 23


### 🔍 Line-by-Line Explanation

1. `cube[1, 2, 3]` supplies one index for each of the three dimensions.
2. All indexing is zero-based, so `1` means the second block, `2` the third row, and `3` the fourth column.
3. The expression selects one scalar value, which is stored in `value`.
4. `print()` displays that value.

## Question 53

**Use a range in one dimension and single indices in the others, and predict the resulting shape.**

In [53]:
cube = np.arange(24).reshape(2, 3, 4)

selected = cube[:, 1, 1:3]
print("Prediction: shape = (2, 2)")
print("Actual shape:", selected.shape)
print(selected)

Prediction: shape = (2, 2)
Actual shape: (2, 2)
[[ 5  6]
 [17 18]]


### 🔍 Line-by-Line Explanation

1. `:` in the first dimension selects both blocks.
2. `1` in the second dimension selects one row from each block.
3. `1:3` in the third dimension selects columns at indices 1 and 2.
4. The selected data therefore has two remaining dimensions: 2 blocks and 2 selected columns.
5. The resulting shape is `(2, 2)`.

## Question 54

**Use fewer indices than dimensions and explain what NumPy returns.**

In [54]:
cube = np.arange(24).reshape(2, 3, 4)

selected = cube[1]
print("Selected shape:", selected.shape)
print(selected)

Selected shape: (3, 4)
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### 🔍 Line-by-Line Explanation

1. `cube` has three dimensions.
2. `cube[1]` supplies an index only for the first dimension.
3. NumPy fixes that dimension and returns everything remaining in the other dimensions.
4. The remaining shape is `(3, 4)`, so the result is a 2D array.

## Question 55

**Deliberately use too many indices and read the resulting error message.**

In [55]:
cube = np.arange(24).reshape(2, 3, 4)

try:
    value = cube[0, 1, 2, 3]
    print(value)
except IndexError as e:
    print("Expected indexing error:", e)

Expected indexing error: too many indices for array: array is 3-dimensional, but 4 were indexed


### 🔍 Line-by-Line Explanation

1. `cube` has only three dimensions, so at most three indices can select a single element.
2. `cube[0, 1, 2, 3]` supplies four indices.
3. NumPy therefore raises an `IndexError` because there is one index too many.
4. `try/except` catches the expected error and prints its message.


# Array Creation Functions

## Question 56

**Create a 4×4 array of all zeros.**

In [56]:
zeros = np.zeros((4, 4), dtype=int)
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### 🔍 Line-by-Line Explanation

1. `np.zeros((4, 4))` creates an array with four rows and four columns.
2. Every element is initialized to zero.
3. `dtype=int` requests integer zeros instead of the default floating-point representation.
4. `print()` displays the complete array.

## Question 57

**Create a 3×3 identity matrix using `np.eye`.**

In [57]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 🔍 Line-by-Line Explanation

1. `np.eye(3)` creates a 3×3 identity matrix.
2. The main diagonal contains `1`s.
3. All off-diagonal positions contain `0`s.
4. This matrix is commonly used as the multiplicative identity in matrix algebra.

## Question 58

**Generate 10 random numbers between 0 and 1 using `np.random.rand`.**

In [58]:
np.random.seed(42)
random_numbers = np.random.rand(10)
print(random_numbers)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]


### 🔍 Line-by-Line Explanation

1. `np.random.seed(42)` makes the legacy random sequence reproducible for this example.
2. `np.random.rand(10)` generates ten random floating-point values in the interval from 0 up to, but not including, 1.
3. `print()` displays the ten generated values.
4. The exact values depend on the random generator implementation, while the seed makes this run reproducible in the same environment.

## Question 59

**Use `np.arange` to create every multiple of 5 from 0 to 50.**

In [59]:
multiples_of_5 = np.arange(0, 51, 5)
print(multiples_of_5)

[ 0  5 10 15 20 25 30 35 40 45 50]


### 🔍 Line-by-Line Explanation

1. `np.arange(start, stop, step)` generates evenly spaced values.
2. `0` is the starting value.
3. `51` is used as the stop value because `arange` excludes the stop, and we want to include 50.
4. `5` is the step, so every value increases by five.
5. The result is every multiple of five from 0 through 50.

## Question 60

**Use `np.linspace` to create exactly 6 evenly spaced numbers between 0 and 100.**

In [60]:
values = np.linspace(0, 100, 6)
print(values)

[  0.  20.  40.  60.  80. 100.]


### 🔍 Line-by-Line Explanation

1. `np.linspace(start, stop, num)` creates a specified number of evenly spaced values.
2. `0` is the starting value and `100` is the ending value.
3. `6` requests exactly six numbers.
4. Because the endpoints are included by default, the spacing is 20: 0, 20, 40, 60, 80, 100.

# ✅ Completion Check

**Total questions solved: 60**

Every solution above is intended to be directly executable. Timing questions are hardware-dependent, so their exact seconds can differ between computers, but the code itself performs the requested comparison. Expected-error questions catch the deliberate exceptions so the notebook can continue executing.

---

## 👨‍💻 About This Course

This **free Python course** was designed and developed by **Muhammad Saad** as a contribution toward making programming education more accessible. I created it to share what I’ve learned with students and beginners who want to learn Python but may not have access to paid courses.

The goal is simple: **to make learning Python easier, accessible, and beginner-friendly.** If this course helps someone learn a new skill or take their first step into programming, then this initiative has achieved its purpose.

If you found this class helpful, feel free to share it with someone who might benefit from it.
